spring:
  application:
    name: contact-service
  profiles:
    active: local
  datasource:
    username: ${POSTGRES_USERNAME:dekapx}
    password: ${POSTGRES_PASSWORD:passw0rd}
    url: jdbc:postgresql://localhost:5432/testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
cache:
  type: caffeine
  cache-names: contacts
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=1m
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${CONTEXT_PATH:/contact-service}

