spring:
  application:
    name: contact-service
  profiles:
    active: local
cache:
  type: caffeine
  cache-names: contacts
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=1m
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${CONTEXT_PATH:/contact-service}

